# Generated by Django 4.2.18 on 2025-02-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_file', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
                ('cnt', models.IntegerField()),
            ],
        ),
    ]
